swagger:
  tag:
    sign-in: '01. 로그인'
    sign-up: '02. 회원가입'
    search: '03. 검색페이지'
    my-page: '04. 마이페이지'
    store: '05. 매장 상세 페이지'
    bookmark: '06. 북마크'
    manager: '07. 매장 관리페이지'
    account: '08. 계정 관리페이지'
    map: '09. 맵 페이지'
    tag: '10. 태그'
    home: '11. 홈 화면 페이지'
    map-data: '12. 서울맵 데이터'
    admin: 'A. 어드민 관련 API'
